//! Report command: generates a human-readable CORTEX_REPORT.md.
//!
//! Produces a Markdown report with:
//! - Top connected functions (most-called nodes)
//! - Dead code candidates
//! - Security findings summary
//! - Community/module boundaries from Leiden detection
//! - Complexity hotspots

use std::fs;
use std::path::Path;
use std::sync::Arc;

use crate::security::{owasp, taint};
use crate::store::db::StoreManager;
use crate::store::queries::{community, graph};
use crate::version::VERSION;

/// Generate the CORTEX_REPORT.md file.
pub fn run(store: &Arc<StoreManager>, output_path: &Path) -> Result<(), anyhow::Error> {
    let conn = store.read_conn();

    let mut report = String::new();

    // Header
    report.push_str(&format!(
        "# Cortex Report\n\n\
         > Generated by cortex v{} | {}\n\n",
        VERSION,
        chrono_now()
    ));

    // Architecture summary
    let arch = graph::get_architecture_summary(&conn)?;
    report.push_str("## Architecture overview\n\n");
    report.push_str(&format!(
        "- **Languages detected:** {}\n",
        arch.languages.join(", ")
    ));
    report.push_str(&format!(
        "- **Total nodes:** {}\n",
        arch.total_nodes
    ));
    report.push_str(&format!(
        "- **Total edges:** {}\n",
        arch.total_edges
    ));
    report.push_str(&format!(
        "- **Files indexed:** {}\n",
        arch.files_indexed
    ));
    report.push_str(&format!(
        "- **Top-level modules:** {}\n\n",
        arch.top_level_modules.join(", ")
    ));

    // Most-connected functions (hotspots)
    report.push_str("## Most-connected functions\n\n");
    report.push_str("Functions with the highest inbound call count. Changes here have the largest blast radius.\n\n");
    report.push_str("| Rank | Function | File | Callers |\n");
    report.push_str("|------|----------|------|---------|\n");

    let hotspots = graph::get_hotspot_nodes(&conn, 10)?;
    for (i, node) in hotspots.iter().enumerate() {
        report.push_str(&format!(
            "| {} | `{}` | {} | {} |\n",
            i + 1,
            node.fqn,
            node.file,
            node.caller_count
        ));
    }
    report.push('\n');

    // Dead code candidates
    report.push_str("## Dead code candidates\n\n");
    report.push_str("Nodes with zero inbound call edges (excluding entry points and test functions).\n\n");

    let dead_code = graph::find_dead_code(&conn, 20)?;
    if dead_code.is_empty() {
        report.push_str("No dead code detected.\n\n");
    } else {
        report.push_str("| Function | File | Kind |\n");
        report.push_str("|----------|------|------|\n");
        for node in &dead_code {
            report.push_str(&format!(
                "| `{}` | {} | {:?} |\n",
                node.fqn, node.file, node.kind
            ));
        }
        report.push('\n');
    }

    // Security findings
    report.push_str("## Security findings\n\n");

    let taint_paths = taint::propagate_taint(store)?;
    let owasp_findings = owasp::scan_owasp_patterns(store)?;

    if taint_paths.is_empty() && owasp_findings.is_empty() {
        report.push_str("No security issues detected.\n\n");
    } else {
        if !taint_paths.is_empty() {
            report.push_str(&format!(
                "### Taint flows ({} found)\n\n\
                 Paths where user input reaches a sensitive sink without sanitization.\n\n",
                taint_paths.len()
            ));
            for path in taint_paths.iter().take(10) {
                report.push_str(&format!(
                    "- `{}` -> `{}` (confidence: {:.0}%)\n",
                    path.source_fqn, path.sink_fqn, path.confidence * 100.0
                ));
            }
            if taint_paths.len() > 10 {
                report.push_str(&format!(
                    "- ... and {} more\n",
                    taint_paths.len() - 10
                ));
            }
            report.push('\n');
        }

        if !owasp_findings.is_empty() {
            report.push_str(&format!(
                "### OWASP patterns ({} found)\n\n",
                owasp_findings.len()
            ));
            for finding in owasp_findings.iter().take(10) {
                report.push_str(&format!(
                    "- **{}** in `{}` ({})\n",
                    finding.owasp_category.as_deref().unwrap_or("Unknown"), finding.node_fqn, finding.description
                ));
            }
            if owasp_findings.len() > 10 {
                report.push_str(&format!(
                    "- ... and {} more\n",
                    owasp_findings.len() - 10
                ));
            }
            report.push('\n');
        }
    }

    // Community detection / module boundaries
    report.push_str("## Module boundaries (Leiden communities)\n\n");
    report.push_str("Detected clusters of tightly-coupled code. High inter-cluster coupling suggests refactoring opportunities.\n\n");

    let communities = community::detect_communities(&conn, None, 0.5)?;
    if communities.communities.is_empty() {
        report.push_str("Not enough edges to detect communities.\n\n");
    } else {
        for (i, comm) in communities.communities.iter().enumerate().take(8) {
            report.push_str(&format!(
                "### Cluster {} ({} nodes, {} files)\n\n",
                i + 1,
                comm.node_count,
                comm.files.len()
            ));
            for file in comm.files.iter().take(5) {
                report.push_str(&format!("- {}\n", file));
            }
            if comm.files.len() > 5 {
                report.push_str(&format!("- ... and {} more files\n", comm.files.len() - 5));
            }
            report.push('\n');
        }
    }

    // Write the report
    fs::write(output_path, &report)?;
    println!("Report written to {}", output_path.display());

    Ok(())
}

/// Simple timestamp without pulling in chrono.
fn chrono_now() -> String {
    use std::time::{SystemTime, UNIX_EPOCH};
    let secs = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap_or_default()
        .as_secs();
    // Format as ISO-ish date (good enough without chrono dependency)
    let days = secs / 86400;
    let years = 1970 + days / 365;
    format!("{}", years)
}
